name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: workaround missing dep in action-web-ext
        working-directory: .github/actions/action-web-ext
        run: npm install
      - name: get version
        id: version
        uses: ./.github/actions/github-action-json-property
        with:
          path: 'manifest.json'
          prop_path: 'version'
      - name: Check version matches tag
        if: github.ref_name != 'v'steps.version.outputs.prop
        run: |
          echo "Error: tag does not match manifest version"
          exit 1
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: install deps
        run: yarn install --immutable
      - name: build
        run: yarn build
        env:
          WEB_EXT_FILENAME: jira-bugzilla-v${{ steps.version.outputs.prop }}.xpi
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.prop }}
          tag_name: v${{ steps.version.outputs.prop }}
      - name: "web-ext sign"
        id: web-ext-sign
        uses: ./.github/actions/action-web-ext
        with:
          cmd: sign
          source: ./web-ext-artifacts/jira-bugzilla-v${{ steps.version.outputs.prop }}.xpi
          channel: unlisted
          apiKey: ${{ secrets.AMO_JWT_ISSUER }}
          apiSecret: ${{ secrets.AMO_JWT_SECRET }}
          timeout: 900000
      - name: upload extension file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ${{steps.web-ext-sign.outputs.target}}
          asset_name: jira-bugzilla-v${{ steps.version.outputs.prop }}.xpi
          asset_content_type: application/x-xpinstall
